application: denovoutils
version: 1
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts
- url: /css
  static_dir: css
- url: /static
  static_dir: static
- url: /.*
  script: app.py

skip_files: |
  .*~ |
  ^\.git/.*

